export const THEME_CATEGORIES: Record<string, { id: string, title: string }> = {
  'cozy_farm': { id: 'th_mes_gestion_nature_animaux', title: 'Thèmes Gestion, Nature & Animaux' },
  'tycoon': { id: 'th_mes_gestion_nature_animaux', title: 'Thèmes Gestion, Nature & Animaux' },
  'aquarium': { id: 'th_mes_gestion_nature_animaux', title: 'Thèmes Gestion, Nature & Animaux' },
  'safari_zoo': { id: 'th_mes_gestion_nature_animaux', title: 'Thèmes Gestion, Nature & Animaux' },
  'city_builder': { id: 'th_mes_gestion_nature_animaux', title: 'Thèmes Gestion, Nature & Animaux' },
  'jurassic': { id: 'th_mes_gestion_nature_animaux', title: 'Thèmes Gestion, Nature & Animaux' },
  'emerald_city': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'coral_reef': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'ember': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'arctic_neon': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'gold_rush': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'midnight_ocean': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'ocean_deep': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'lava': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'forest_dark': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'parchment': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'ice_cave': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'aurora': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'desert_night': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'vapor': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'champagne': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'inferno': { id: 'th_mes_classiques_16_id_es', title: 'Thèmes Classiques (16 idées)' },
  'halloween': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'christmas': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'spring': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'easter': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'summer': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'winter': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'autumn': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'chandeleur': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'epiphanie': { id: 'th_mes_saisonniers_v_nementiels_9_th_mes_int_gr_s', title: 'Thèmes Saisonniers & Événementiels (9 thèmes intégrés)' },
  'retro_pixel': { id: 'th_mes_gaming_univers', title: 'Thèmes Gaming / Univers' },
  'ps2_era': { id: 'th_mes_gaming_univers', title: 'Thèmes Gaming / Univers' },
  'game_boy': { id: 'th_mes_gaming_univers', title: 'Thèmes Gaming / Univers' },
  'retro_arcade': { id: 'th_mes_gaming_univers', title: 'Thèmes Gaming / Univers' },
  'egypte_antique': { id: 'th_mes_g_ographiques_culturels', title: 'Thèmes Géographiques / Culturels' },
  'viking_norse': { id: 'th_mes_g_ographiques_culturels', title: 'Thèmes Géographiques / Culturels' },
  'tundra': { id: 'th_mes_g_ographiques_culturels', title: 'Thèmes Géographiques / Culturels' },
  'andalousie': { id: 'th_mes_g_ographiques_culturels', title: 'Thèmes Géographiques / Culturels' },
  'medieval_kingdom': { id: 'th_mes_historiques_fantasy', title: 'Thèmes Historiques / Fantasy' },
  'roman_empire': { id: 'th_mes_historiques_fantasy', title: 'Thèmes Historiques / Fantasy' },
  'age_of_sail': { id: 'th_mes_historiques_fantasy', title: 'Thèmes Historiques / Fantasy' },
  'aztec': { id: 'th_mes_historiques_fantasy', title: 'Thèmes Historiques / Fantasy' },
  'elven_forest': { id: 'th_mes_historiques_fantasy', title: 'Thèmes Historiques / Fantasy' },
  'deep_sea': { id: 'th_mes_historiques_fantasy', title: 'Thèmes Historiques / Fantasy' },
  'nebula': { id: 'th_mes_astronomie_espace_futurisme', title: 'Thèmes Astronomie / Espace / Futurisme' },
  'black_hole': { id: 'th_mes_astronomie_espace_futurisme', title: 'Thèmes Astronomie / Espace / Futurisme' },
  'quantum': { id: 'th_mes_astronomie_espace_futurisme', title: 'Thèmes Astronomie / Espace / Futurisme' },
  'mars_colony': { id: 'th_mes_astronomie_espace_futurisme', title: 'Thèmes Astronomie / Espace / Futurisme' },
  'stargate': { id: 'th_mes_astronomie_espace_futurisme', title: 'Thèmes Astronomie / Espace / Futurisme' },
  'deep_space': { id: 'th_mes_astronomie_espace_futurisme', title: 'Thèmes Astronomie / Espace / Futurisme' },
  'upside_down': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'replicant': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'dino_dna': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'isla_nublar': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'whip_hat': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'delorean': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'skynet': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'gargantua': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'unsinkable': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'butterfly_effect': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'walking_sim': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'broken_screen': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  '221b': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'the_truth': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'reactor_4': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'dark_passenger': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'nakatomi': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'proton_pack': { id: 'th_mes_films_s_ries_d_blocables_via_les_jeux', title: 'Thèmes Films & Séries (Déblocables via les Jeux)' },
  'mushroom_kingdom': { id: 'th_mes_jeux_vid_o', title: 'Thèmes Jeux Vidéo' },
  'kanto': { id: 'th_mes_jeux_vid_o', title: 'Thèmes Jeux Vidéo' },
  'green_hill': { id: 'th_mes_jeux_vid_o', title: 'Thèmes Jeux Vidéo' },
  'sic_parvis_magna': { id: 'th_mes_jeux_vid_o', title: 'Thèmes Jeux Vidéo' },
  'tomb_raider': { id: 'th_mes_jeux_vid_o', title: 'Thèmes Jeux Vidéo' },
  'los_santos': { id: 'th_mes_jeux_vid_o', title: 'Thèmes Jeux Vidéo' },
  'infinity': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'multiverse': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'galaxy_far_away': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'hogwarts': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'forgotten_realms': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'arrakis': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'psychohistory': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'the_construct': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'cybertron': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'forks': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'pandora': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'once_upon_a_dream': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'luxo': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'castle_rock': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'wardrobe': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'panem': { id: 'th_mes_univers_entiers', title: 'Thèmes Univers Entiers' },
  'web_slinger': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'the_dark_knight': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'stark_tech': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'man_of_steel': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'speed_force': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'clown_prince': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'first_avenger': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'god_of_thunder': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'gamma_smash': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'red_room': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'weapon_x': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'wakanda_forever': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'sorcerer_supreme': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'symbiote': { id: 'th_mes_super_h_ros_marvel_dc', title: 'Thèmes Super-Héros (Marvel & DC)' },
  'andy_s_room': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'motunui': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'scare_floor': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'route_66': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'arendelle': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'eac': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'agrabah': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'pride_rock': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'headquarters': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'enchanted_rose': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'dragon_warrior': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'paradise_falls': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'gusteau_s': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'axiom': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'olympus': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'neverland': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'bella_notte': { id: 'th_mes_disney_pixar_par_film', title: 'Thèmes Disney / Pixar (Par Film)' },
  'ici_c_est_paris': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'citizens': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'red_devils': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'ynwa': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'gunners': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'los_blancos': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'blaugrana': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'colchoneros': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'mia_san_mia': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'bianconeri': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'rossoneri': { id: 'th_mes_clubs_de_sport', title: 'Thèmes Clubs de Sport' },
  'pony_car': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'm_power': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'quattro': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'silver_star': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'stingray': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'carrera': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'rosso_corsa': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'sant_agata': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'db_series': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'flying_b': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'molsheim': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'spirit_of_ecstasy': { id: 'th_mes_automobile_marques_iconiques', title: 'Thèmes Automobile (Marques Iconiques)' },
  'danger_zone': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'winden': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'berk': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'phone_home': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'mystery_machine': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'flux': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'street_football': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'lasagna': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'cambrioleur': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'glade': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  '007': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'manners': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'flight_828': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'sarsaparilla': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'potion_magique': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'reporter': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'imhotep': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'ahkmenrah': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'kevin!': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'slappy': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'lv_426': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'welcome_to_earth': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'street_racing': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'imf': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'jungle_board': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'neuralyzer': { id: 'th_mes_films_s_ries_par_d_faut_ou_actions', title: 'Thèmes Films & Séries (Par Défaut ou Actions)' },
  'eruption': { id: 'th_mes_catastrophes_naturelles_m_ta', title: 'Thèmes Catastrophes Naturelles (Méta)' },
  'tsunami': { id: 'th_mes_catastrophes_naturelles_m_ta', title: 'Thèmes Catastrophes Naturelles (Méta)' },
  'twister': { id: 'th_mes_catastrophes_naturelles_m_ta', title: 'Thèmes Catastrophes Naturelles (Méta)' },
  'whiteout': { id: 'th_mes_catastrophes_naturelles_m_ta', title: 'Thèmes Catastrophes Naturelles (Méta)' },
  'meteor_strike': { id: 'th_mes_catastrophes_naturelles_m_ta', title: 'Thèmes Catastrophes Naturelles (Méta)' },
  'sinkhole': { id: 'th_mes_catastrophes_naturelles_m_ta', title: 'Thèmes Catastrophes Naturelles (Méta)' },
};
