import { ExternalGameDetails } from '@/services/externalApiService'

export interface ThemeRule {
  id: string
  name: string
  condition: string
  max: number
  evaluate: (games: ExternalGameDetails[]) => number
}

export const THEME_RULES: ThemeRule[] = [
  { id: 'cozy_farm', name: 'Cozy Farm', condition: 'Trophée cozy_farmer', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'tycoon', name: 'Tycoon', condition: 'Trophée tycoon_master', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'aquarium', name: 'Aquarium', condition: 'Trophée zookeeper', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'safari_zoo', name: 'Safari Zoo', condition: 'Trophée zookeeper', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'city_builder', name: 'City Builder', condition: 'Trophée city_mayor', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'jurassic', name: 'Jurassic', condition: 'Trophée dino_dna', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'emerald_city', name: 'Emerald City', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'coral_reef', name: 'Coral Reef', condition: 'Trophée `theme_abyss`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ember', name: 'Ember', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'arctic_neon', name: 'Arctic Neon', condition: 'Trophée `theme_cyberpunk`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'gold_rush', name: 'Gold Rush', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'midnight_ocean', name: 'Midnight Ocean', condition: 'Trophée `theme_abyss`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ocean_deep', name: 'Ocean Deep', condition: 'Trophée `theme_abyss`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'lava', name: 'Lava', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'forest_dark', name: 'Forest Dark', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'parchment', name: 'Parchment', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ice_cave', name: 'Ice Cave', condition: 'Trophée `theme_arctic`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'aurora', name: 'Aurora', condition: 'Trophée `theme_neon`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'desert_night', name: 'Desert Night', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'vapor', name: 'Vapor', condition: 'Trophée `theme_neon`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'champagne', name: 'Champagne', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'inferno', name: 'Inferno', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'halloween', name: 'Halloween', condition: 'Événementielle', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'christmas', name: 'Christmas', condition: 'Événementielle', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'spring', name: 'Spring', condition: 'Saisonnière', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'easter', name: 'Easter', condition: 'Événementielle', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'summer', name: 'Summer', condition: 'Saisonnière', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'winter', name: 'Winter', condition: 'Saisonnière', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'autumn', name: 'Autumn', condition: 'Saisonnière', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'chandeleur', name: 'Chandeleur', condition: 'Événementielle', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'epiphanie', name: 'Epiphanie', condition: 'Événementielle', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'retro_pixel', name: 'Retro Pixel', condition: 'Trophée `retro_gamer`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ps2_era', name: 'PS2 Era', condition: 'Trophée `guerre_consoles`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'game_boy', name: 'Game Boy', condition: 'Trophée `nostalgie`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'retro_arcade', name: 'Retro Arcade', condition: 'Trophée `shortcut_master`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'egypte_antique', name: 'Egypte Antique', condition: 'Ajouter 3 jeux "Aventure"', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('aventure') || (game.genres?.some(gen => gen.toLowerCase().includes('aventure')) || game.tags?.some(t => t.toLowerCase().includes('aventure')))).length },
  { id: 'viking_norse', name: 'Viking Norse', condition: 'Trophée `shortcut_pro`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'tundra', name: 'Tundra', condition: 'Ajouter 4 jeux "Aventure"', max: 4, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('aventure') || (game.genres?.some(gen => gen.toLowerCase().includes('aventure')) || game.tags?.some(t => t.toLowerCase().includes('aventure')))).length },
  { id: 'andalousie', name: 'Andalousie', condition: 'Ajouter 7 jeux "Aventure"', max: 7, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('aventure') || (game.genres?.some(gen => gen.toLowerCase().includes('aventure')) || game.tags?.some(t => t.toLowerCase().includes('aventure')))).length },
  { id: 'medieval_kingdom', name: 'Medieval Kingdom', condition: 'Trophée `mon_precieux`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'roman_empire', name: 'Roman Empire', condition: 'Trophée `coup_de_foudre`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'age_of_sail', name: 'Age of Sail', condition: 'Trophée `critique_art`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'aztec', name: 'Aztec', condition: 'Trophée `data_analyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'elven_forest', name: 'Elven Forest', condition: 'Ajouter 3 jeux "RPG"', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('rpg') || (game.genres?.some(gen => gen.toLowerCase().includes('rpg')) || game.tags?.some(t => t.toLowerCase().includes('rpg')))).length },
  { id: 'deep_sea', name: 'Deep Sea', condition: 'Ajouter 4 jeux "RPG"', max: 4, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('rpg') || (game.genres?.some(gen => gen.toLowerCase().includes('rpg')) || game.tags?.some(t => t.toLowerCase().includes('rpg')))).length },
  { id: 'nebula', name: 'Nebula', condition: 'Trophée `shortcut_novice`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'black_hole', name: 'Black Hole', condition: 'Trophée `insomniaque`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'quantum', name: 'Quantum', condition: 'Ajouter 3 jeux "Science-Fiction"', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('science-fiction') || (game.genres?.some(gen => gen.toLowerCase().includes('science-fiction')) || game.tags?.some(t => t.toLowerCase().includes('science-fiction')))).length },
  { id: 'mars_colony', name: 'Mars Colony', condition: 'Ajouter 4 jeux "Science-Fiction"', max: 4, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('science-fiction') || (game.genres?.some(gen => gen.toLowerCase().includes('science-fiction')) || game.tags?.some(t => t.toLowerCase().includes('science-fiction')))).length },
  { id: 'stargate', name: 'Stargate', condition: 'Ajouter 7 jeux "Science-Fiction"', max: 7, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('science-fiction') || (game.genres?.some(gen => gen.toLowerCase().includes('science-fiction')) || game.tags?.some(t => t.toLowerCase().includes('science-fiction')))).length },
  { id: 'deep_space', name: 'Deep Space', condition: 'Ajouter 10 jeux "Science-Fiction"', max: 10, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('science-fiction') || (game.genres?.some(gen => gen.toLowerCase().includes('science-fiction')) || game.tags?.some(t => t.toLowerCase().includes('science-fiction')))).length },
  { id: 'upside_down', name: 'Upside Down', condition: 'Ajouter 1 jeu "Horreur/Thriller"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('horreur/thriller') || (game.genres?.some(gen => gen.toLowerCase().includes('horreur/thriller')) || game.tags?.some(t => t.toLowerCase().includes('horreur/thriller')))).length },
  { id: 'replicant', name: 'Replicant', condition: 'Ajouter 3 jeux "Cyberpunk"', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('cyberpunk') || (game.genres?.some(gen => gen.toLowerCase().includes('cyberpunk')) || game.tags?.some(t => t.toLowerCase().includes('cyberpunk')))).length },
  { id: 'dino_dna', name: 'Dino DNA', condition: 'Ajouter 1 jeu : Jurassic Park', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('jurassic park') || (game.genres?.some(gen => gen.toLowerCase().includes('jurassic park')) || game.tags?.some(t => t.toLowerCase().includes('jurassic park')))).length },
  { id: 'isla_nublar', name: 'Isla Nublar', condition: 'Ajouter 3 jeux : Jurassic Park', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('jurassic park') || (game.genres?.some(gen => gen.toLowerCase().includes('jurassic park')) || game.tags?.some(t => t.toLowerCase().includes('jurassic park')))).length },
  { id: 'whip_hat', name: 'Whip & Hat', condition: 'Ajouter 1 jeu : Indiana Jones', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('indiana jones') || (game.genres?.some(gen => gen.toLowerCase().includes('indiana jones')) || game.tags?.some(t => t.toLowerCase().includes('indiana jones')))).length },
  { id: 'delorean', name: 'Delorean', condition: 'Trophée `voyage_temps`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'skynet', name: 'Skynet', condition: 'Ajouter 1 jeu : Terminator', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('terminator') || (game.genres?.some(gen => gen.toLowerCase().includes('terminator')) || game.tags?.some(t => t.toLowerCase().includes('terminator')))).length },
  { id: 'gargantua', name: 'Gargantua', condition: 'Ajouter 2 jeux dans l\'Espace', max: 2, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'unsinkable', name: 'Unsinkable', condition: 'Ajouter 3 jeux "Narratifs"', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('narratifs') || (game.genres?.some(gen => gen.toLowerCase().includes('narratifs')) || game.tags?.some(t => t.toLowerCase().includes('narratifs')))).length },
  { id: 'butterfly_effect', name: 'Butterfly Effect', condition: 'Ajouter 3 jeux "Narratifs"', max: 3, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('narratifs') || (game.genres?.some(gen => gen.toLowerCase().includes('narratifs')) || game.tags?.some(t => t.toLowerCase().includes('narratifs')))).length },
  { id: 'walking_sim', name: 'Walking Sim', condition: 'Ajouter 1 jeux "Narratifs"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('narratifs') || (game.genres?.some(gen => gen.toLowerCase().includes('narratifs')) || game.tags?.some(t => t.toLowerCase().includes('narratifs')))).length },
  { id: 'broken_screen', name: 'Broken Screen', condition: 'Ajouter 1 jeux "Cyberpunk"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('cyberpunk') || (game.genres?.some(gen => gen.toLowerCase().includes('cyberpunk')) || game.tags?.some(t => t.toLowerCase().includes('cyberpunk')))).length },
  { id: '221b', name: '221B', condition: 'Ajouter 1 jeux "Enquête"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('enquête') || (game.genres?.some(gen => gen.toLowerCase().includes('enquête')) || game.tags?.some(t => t.toLowerCase().includes('enquête')))).length },
  { id: 'the_truth', name: 'The Truth', condition: 'Ajouter 1 jeux "Mystère"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('mystère') || (game.genres?.some(gen => gen.toLowerCase().includes('mystère')) || game.tags?.some(t => t.toLowerCase().includes('mystère')))).length },
  { id: 'reactor_4', name: 'Reactor 4', condition: 'Ajouter 1 jeux "Post-Apo"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('post-apo') || (game.genres?.some(gen => gen.toLowerCase().includes('post-apo')) || game.tags?.some(t => t.toLowerCase().includes('post-apo')))).length },
  { id: 'dark_passenger', name: 'Dark Passenger', condition: 'Ajouter 1 jeux "Horreur/Sanglant"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('horreur/sanglant') || (game.genres?.some(gen => gen.toLowerCase().includes('horreur/sanglant')) || game.tags?.some(t => t.toLowerCase().includes('horreur/sanglant')))).length },
  { id: 'nakatomi', name: 'Nakatomi', condition: 'Ajouter 1 jeux "Action"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('action') || (game.genres?.some(gen => gen.toLowerCase().includes('action')) || game.tags?.some(t => t.toLowerCase().includes('action')))).length },
  { id: 'proton_pack', name: 'Proton Pack', condition: 'Ajouter 1 jeu "Surnaturel"', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('surnaturel') || (game.genres?.some(gen => gen.toLowerCase().includes('surnaturel')) || game.tags?.some(t => t.toLowerCase().includes('surnaturel')))).length },
  { id: 'mushroom_kingdom', name: 'Mushroom Kingdom', condition: 'Trophée `its_a_me`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'kanto', name: 'Kanto', condition: 'Ajouter 1 jeu : Pokémon', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('pokémon') || (game.genres?.some(gen => gen.toLowerCase().includes('pokémon')) || game.tags?.some(t => t.toLowerCase().includes('pokémon')))).length },
  { id: 'green_hill', name: 'Green Hill', condition: 'Ajouter 1 jeu : Sonic', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('sonic') || (game.genres?.some(gen => gen.toLowerCase().includes('sonic')) || game.tags?.some(t => t.toLowerCase().includes('sonic')))).length },
  { id: 'sic_parvis_magna', name: 'Sic Parvis Magna', condition: 'Ajouter 1 jeu : Uncharted', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('uncharted') || (game.genres?.some(gen => gen.toLowerCase().includes('uncharted')) || game.tags?.some(t => t.toLowerCase().includes('uncharted')))).length },
  { id: 'tomb_raider', name: 'Tomb Raider', condition: 'Ajouter 1 jeu : Tomb Raider', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('tomb raider') || (game.genres?.some(gen => gen.toLowerCase().includes('tomb raider')) || game.tags?.some(t => t.toLowerCase().includes('tomb raider')))).length },
  { id: 'los_santos', name: 'Los Santos', condition: 'Ajouter 1 jeu : GTA', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('gta') || (game.genres?.some(gen => gen.toLowerCase().includes('gta')) || game.tags?.some(t => t.toLowerCase().includes('gta')))).length },
  { id: 'infinity', name: 'Infinity', condition: 'Trophée `infinity_stones`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'multiverse', name: 'Multiverse', condition: 'Trophée `justice_league`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'galaxy_far_away', name: 'Galaxy Far Away', condition: 'Trophée `may_the_force`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'hogwarts', name: 'Hogwarts', condition: 'Ajouter 1 jeu : Harry Potter', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('harry potter') || (game.genres?.some(gen => gen.toLowerCase().includes('harry potter')) || game.tags?.some(t => t.toLowerCase().includes('harry potter')))).length },
  { id: 'forgotten_realms', name: 'Forgotten Realms', condition: 'Ajouter 1 jeux : D&D / Baldur\'s Gate', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('d&d / baldur\'s gate') || (game.genres?.some(gen => gen.toLowerCase().includes('d&d / baldur\'s gate')) || game.tags?.some(t => t.toLowerCase().includes('d&d / baldur\'s gate')))).length },
  { id: 'arrakis', name: 'Arrakis', condition: 'Ajouter 1 jeu : Dune', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('dune') || (game.genres?.some(gen => gen.toLowerCase().includes('dune')) || game.tags?.some(t => t.toLowerCase().includes('dune')))).length },
  { id: 'psychohistory', name: 'Psychohistory', condition: 'Ajouter 1 jeux : Sci-Fi Spatiale', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('sci-fi spatiale') || (game.genres?.some(gen => gen.toLowerCase().includes('sci-fi spatiale')) || game.tags?.some(t => t.toLowerCase().includes('sci-fi spatiale')))).length },
  { id: 'the_construct', name: 'The Construct', condition: 'Ajouter 1 jeu : Matrix', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('matrix') || (game.genres?.some(gen => gen.toLowerCase().includes('matrix')) || game.tags?.some(t => t.toLowerCase().includes('matrix')))).length },
  { id: 'cybertron', name: 'Cybertron', condition: 'Ajouter 1 jeu : Transformers', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('transformers') || (game.genres?.some(gen => gen.toLowerCase().includes('transformers')) || game.tags?.some(t => t.toLowerCase().includes('transformers')))).length },
  { id: 'forks', name: 'Forks', condition: 'Ajouter 1 jeux : Vampires/Loups-Garous', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('vampires/loups-garous') || (game.genres?.some(gen => gen.toLowerCase().includes('vampires/loups-garous')) || game.tags?.some(t => t.toLowerCase().includes('vampires/loups-garous')))).length },
  { id: 'pandora', name: 'Pandora', condition: 'Ajouter 1 jeu : Avatar', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('avatar') || (game.genres?.some(gen => gen.toLowerCase().includes('avatar')) || game.tags?.some(t => t.toLowerCase().includes('avatar')))).length },
  { id: 'once_upon_a_dream', name: 'Once Upon a Dream', condition: 'Trophée `retro_gamer`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'luxo', name: 'Luxo', condition: 'Ajouter 1 jeux : Pixar', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('pixar') || (game.genres?.some(gen => gen.toLowerCase().includes('pixar')) || game.tags?.some(t => t.toLowerCase().includes('pixar')))).length },
  { id: 'castle_rock', name: 'Castle Rock', condition: 'Ajouter 1 jeux : Horreur/Surnaturel', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('horreur/surnaturel') || (game.genres?.some(gen => gen.toLowerCase().includes('horreur/surnaturel')) || game.tags?.some(t => t.toLowerCase().includes('horreur/surnaturel')))).length },
  { id: 'wardrobe', name: 'Wardrobe', condition: 'Ajouter 1 jeux : Fantasy/Narnia', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('fantasy/narnia') || (game.genres?.some(gen => gen.toLowerCase().includes('fantasy/narnia')) || game.tags?.some(t => t.toLowerCase().includes('fantasy/narnia')))).length },
  { id: 'panem', name: 'Panem', condition: 'Ajouter 1 jeux : Survie/Battle Royale', max: 1, evaluate: (g) => g.filter(game => game.name.toLowerCase().includes('survie/battle royale') || (game.genres?.some(gen => gen.toLowerCase().includes('survie/battle royale')) || game.tags?.some(t => t.toLowerCase().includes('survie/battle royale')))).length },
  { id: 'web_slinger', name: 'Web-Slinger', condition: 'Trophée `spider_web`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'the_dark_knight', name: 'The Dark Knight', condition: 'Trophée `nocturne`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'stark_tech', name: 'Stark Tech', condition: 'Trophée `i_am_iron_man`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'man_of_steel', name: 'Man of Steel', condition: '1 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'speed_force', name: 'Speed Force', condition: 'Trophée `speedrunner`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'clown_prince', name: 'Clown Prince', condition: '1 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'first_avenger', name: 'First Avenger', condition: '2 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'god_of_thunder', name: 'God of Thunder', condition: '2 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'gamma_smash', name: 'Gamma Smash', condition: '3 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'red_room', name: 'Red Room', condition: '3 jeux Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'weapon_x', name: 'Weapon X', condition: '4 jeux Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'wakanda_forever', name: 'Wakanda Forever', condition: '4 jeux Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'sorcerer_supreme', name: 'Sorcerer Supreme', condition: '5 jeux Super-Héros', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'symbiote', name: 'Symbiote', condition: '5 jeux Spider-man', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'andy_s_room', name: 'Andy\'s Room', condition: '1 jeu Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'motunui', name: 'Motunui', condition: '1 jeu Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'scare_floor', name: 'Scare Floor', condition: '2 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'route_66', name: 'Route 66', condition: '2 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'arendelle', name: 'Arendelle', condition: '3 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'eac', name: 'EAC', condition: '3 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'agrabah', name: 'Agrabah', condition: '3 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'pride_rock', name: 'Pride Rock', condition: '4 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'headquarters', name: 'Headquarters', condition: 'Trophée `indecis`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'enchanted_rose', name: 'Enchanted Rose', condition: '4 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'dragon_warrior', name: 'Dragon Warrior', condition: '4 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'paradise_falls', name: 'Paradise Falls', condition: '5 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'gusteau_s', name: 'Gusteau\'s', condition: '5 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'axiom', name: 'Axiom', condition: '5 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'olympus', name: 'Olympus', condition: '5 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'neverland', name: 'Neverland', condition: '6 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'bella_notte', name: 'Bella Notte', condition: '6 jeux Familial/Cartoon', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ici_c_est_paris', name: 'Ici c\'est Paris', condition: '1 jeu de Football', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'citizens', name: 'Citizens', condition: '1 jeu de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'red_devils', name: 'Red Devils', condition: '2 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ynwa', name: 'YNWA', condition: '2 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'gunners', name: 'Gunners', condition: '3 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'los_blancos', name: 'Los Blancos', condition: '3 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'blaugrana', name: 'Blaugrana', condition: '4 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'colchoneros', name: 'Colchoneros', condition: '5 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'mia_san_mia', name: 'Mia San Mia', condition: '5 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'bianconeri', name: 'Bianconeri', condition: '7 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'rossoneri', name: 'Rossoneri', condition: '8 jeux de Sport', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'pony_car', name: 'Pony Car', condition: '1 jeu de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'm_power', name: 'M-Power', condition: '1 jeu de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'quattro', name: 'Quattro', condition: '2 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'silver_star', name: 'Silver Star', condition: '2 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'stingray', name: 'Stingray', condition: '3 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'carrera', name: 'Carrera', condition: '3 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'rosso_corsa', name: 'Rosso Corsa', condition: '4 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'sant_agata', name: 'Sant\'Agata', condition: '5 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'db_series', name: 'DB Series', condition: '5 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'flying_b', name: 'Flying B', condition: '7 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'molsheim', name: 'Molsheim', condition: '8 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'spirit_of_ecstasy', name: 'Spirit of Ecstasy', condition: '10 jeux de Course', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'danger_zone', name: 'Danger Zone', condition: 'Trophée `theme_neon`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'winden', name: 'Winden', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'berk', name: 'Berk', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'phone_home', name: 'Phone Home', condition: 'Trophée `appel_maison`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'mystery_machine', name: 'Mystery Machine', condition: 'Trophée `tag_master`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'flux', name: 'Flux', condition: 'Trophée `import_export`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'street_football', name: 'Street Football', condition: 'Trophée `multi_device`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'lasagna', name: 'Lasagna', condition: 'Trophée `coup_de_foudre`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'cambrioleur', name: 'Cambrioleur', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'glade', name: 'Glade', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: '007', name: '007', condition: 'Trophée `agent_secret`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'manners', name: 'Manners', condition: 'Trophée `critique_art`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'flight_828', name: 'Flight 828', condition: 'Trophée `data_analyst`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'sarsaparilla', name: 'Sarsaparilla', condition: 'Trophée `theme_abyss`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'potion_magique', name: 'Potion Magique', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'reporter', name: 'Reporter', condition: 'Trophée `mon_precieux`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'imhotep', name: 'Imhotep', condition: 'Ajouter 1 jeux Égypte/Momies', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'ahkmenrah', name: 'Ahkmenrah', condition: 'Ajouter 1 jeux Musée/Histoire', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'kevin!', name: 'Kevin!', condition: 'Ajouter 1 jeu Défense/Pièges', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'slappy', name: 'Slappy', condition: 'Ajouter 1 jeux Horreur Familiale', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'lv_426', name: 'LV-426', condition: 'Ajouter 1 jeux Horreur Spatiale', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'welcome_to_earth', name: 'Welcome to Earth', condition: 'Ajouter 1 jeux Invasion', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'street_racing', name: 'Street Racing', condition: 'Ajouter 1 jeux Course Urbaine', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'imf', name: 'IMF', condition: 'Ajouter 1 jeux Espionnage', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'jungle_board', name: 'Jungle Board', condition: 'Ajouter 1 jeux Aventure Jungle', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'neuralyzer', name: 'Neuralyzer', condition: 'Ajouter 1 jeux Extraterrestres', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'eruption', name: 'Eruption', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'tsunami', name: 'Tsunami', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'twister', name: 'Twister', condition: 'Trophée `speedrunner`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'whiteout', name: 'Whiteout', condition: 'Trophée `hibernation`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'meteor_strike', name: 'Meteor Strike', condition: 'Trophée `impact_massif`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'sinkhole', name: 'Sinkhole', condition: 'Trophée `long_journey`', max: 1, evaluate: (g) => 0 /* Simulé via trophée */ },
  { id: 'web_slinger', name: 'Web-Slinger', condition: 'Trophée `spider_web`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'the_dark_knight', name: 'The Dark Knight', condition: 'Trophée `nocturne`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'stark_tech', name: 'Stark Tech', condition: 'Trophée `i_am_iron_man`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'man_of_steel', name: 'Man of Steel', condition: '1 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'speed_force', name: 'Speed Force', condition: 'Trophée `speedrunner`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'clown_prince', name: 'Clown Prince', condition: '1 jeu Super-Héros', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'first_avenger', name: 'First Avenger', condition: '2 jeu Super-Héros', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'god_of_thunder', name: 'God of Thunder', condition: '2 jeu Super-Héros', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'gamma_smash', name: 'Gamma Smash', condition: '3 jeu Super-Héros', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'red_room', name: 'Red Room', condition: '3 jeux Super-Héros', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'weapon_x', name: 'Weapon X', condition: '4 jeux Super-Héros', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'wakanda_forever', name: 'Wakanda Forever', condition: '4 jeux Super-Héros', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'sorcerer_supreme', name: 'Sorcerer Supreme', condition: '5 jeux Super-Héros', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'symbiote', name: 'Symbiote', condition: '5 jeux Spider-man', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'andys_room', name: "Andy's Room", condition: '1 jeu Familial/Cartoon', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'motunui', name: 'Motunui', condition: '1 jeu Familial/Cartoon', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'scare_floor', name: 'Scare Floor', condition: '2 jeux Familial/Cartoon', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'route_66', name: 'Route 66', condition: '2 jeux Familial/Cartoon', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'arendelle', name: 'Arendelle', condition: '3 jeux Familial/Cartoon', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'eac', name: 'EAC', condition: '3 jeux Familial/Cartoon', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'agrabah', name: 'Agrabah', condition: '3 jeux Familial/Cartoon', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'pride_rock', name: 'Pride Rock', condition: '4 jeux Familial/Cartoon', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'headquarters', name: 'Headquarters', condition: 'Trophée `indecis`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'enchanted_rose', name: 'Enchanted Rose', condition: '4 jeux Familial/Cartoon', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'dragon_warrior', name: 'Dragon Warrior', condition: '4 jeux Familial/Cartoon', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'paradise_falls', name: 'Paradise Falls', condition: '5 jeux Familial/Cartoon', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'gusteaus', name: "Gusteau's", condition: '5 jeux Familial/Cartoon', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'axiom', name: 'Axiom', condition: '5 jeux Familial/Cartoon', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'olympus', name: 'Olympus', condition: '5 jeux Familial/Cartoon', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'neverland', name: 'Neverland', condition: '6 jeux Familial/Cartoon', max: 6, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'bella_notte', name: 'Bella Notte', condition: '6 jeux Familial/Cartoon', max: 6, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'ici_cest_paris', name: "Ici c'est Paris", condition: '1 jeu de Football', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'citizens', name: 'Citizens', condition: '1 jeu de Sport', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'red_devils', name: 'Red Devils', condition: '2 jeux de Sport', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'ynwa', name: 'YNWA', condition: '2 jeux de Sport', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'gunners', name: 'Gunners', condition: '3 jeux de Sport', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'los_blancos', name: 'Los Blancos', condition: '3 jeux de Sport', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'blaugrana', name: 'Blaugrana', condition: '4 jeux de Sport', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'colchoneros', name: 'Colchoneros', condition: '5 jeux de Sport', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'mia_san_mia', name: 'Mia San Mia', condition: '5 jeux de Sport', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'bianconeri', name: 'Bianconeri', condition: '7 jeux de Sport', max: 7, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'rossoneri', name: 'Rossoneri', condition: '8 jeux de Sport', max: 8, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'pony_car', name: 'Pony Car', condition: '1 jeu de Course', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'm_power', name: 'M-Power', condition: '1 jeu de Course', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'quattro', name: 'Quattro', condition: '2 jeux de Course', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'silver_star', name: 'Silver Star', condition: '2 jeux de Course', max: 2, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'stingray', name: 'Stingray', condition: '3 jeux de Course', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'carrera', name: 'Carrera', condition: '3 jeux de Course', max: 3, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'rosso_corsa', name: 'Rosso Corsa', condition: '4 jeux de Course', max: 4, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'santagata', name: "Sant'Agata", condition: '5 jeux de Course', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'db_series', name: 'DB Series', condition: '5 jeux de Course', max: 5, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'flying_b', name: 'Flying B', condition: '7 jeux de Course', max: 7, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'molsheim', name: 'Molsheim', condition: '8 jeux de Course', max: 8, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'spirit_of_ecstasy', name: 'Spirit of Ecstasy', condition: '10 jeux de Course', max: 10, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'danger_zone', name: 'Danger Zone', condition: 'Trophée `theme_neon`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'winden', name: 'Winden', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'berk', name: 'Berk', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'phone_home', name: 'Phone Home', condition: 'Trophée `appel_maison`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'mystery_machine', name: 'Mystery Machine', condition: 'Trophée `tag_master`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'flux', name: 'Flux', condition: 'Trophée `import_export`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'street_football', name: 'Street Football', condition: 'Trophée `multi_device`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'lasagna', name: 'Lasagna', condition: 'Trophée `coup_de_foudre`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'cambrioleur', name: 'Cambrioleur', condition: 'Trophée `theme_amethyst`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'glade', name: 'Glade', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: '007', name: '007', condition: 'Trophée `agent_secret`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'manners', name: 'Manners', condition: 'Trophée `critique_art`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'flight_828', name: 'Flight 828', condition: 'Trophée `data_analyst`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'sarsaparilla', name: 'Sarsaparilla', condition: 'Trophée `theme_abyss`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'potion_magique', name: 'Potion Magique', condition: 'Trophée `theme_dune`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'reporter', name: 'Reporter', condition: 'Trophée `mon_precieux`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'imhotep', name: 'Imhotep', condition: 'Ajouter 1 jeux Égypte/Momies', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'ahkmenrah', name: 'Ahkmenrah', condition: 'Ajouter 1 jeux Musée/Histoire', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'kevin', name: 'Kevin!', condition: 'Ajouter 1 jeu Défense/Pièges', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'slappy', name: 'Slappy', condition: 'Ajouter 1 jeux Horreur Familiale', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'lv_426', name: 'LV-426', condition: 'Ajouter 1 jeux Horreur Spatiale', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'welcome_to_earth', name: 'Welcome to Earth', condition: 'Ajouter 1 jeux Invasion', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'street_racing', name: 'Street Racing', condition: 'Ajouter 1 jeux Course Urbaine', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'imf', name: 'IMF', condition: 'Ajouter 1 jeux Espionnage', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'jungle_board', name: 'Jungle Board', condition: 'Ajouter 1 jeux Aventure Jungle', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'neuralyzer', name: 'Neuralyzer', condition: 'Ajouter 1 jeux Extraterrestres', max: 1, evaluate: (g) => 0 /* À implémenter */ },
  { id: 'eruption', name: 'Eruption', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'tsunami', name: 'Tsunami', condition: 'Trophée `theme_dracula`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'twister', name: 'Twister', condition: 'Trophée `speedrunner`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'whiteout', name: 'Whiteout', condition: 'Trophée `hibernation`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'meteor_strike', name: 'Meteor Strike', condition: 'Trophée `impact_massif`', max: 1, evaluate: (g) => 0 /* Simulé */ },
  { id: 'sinkhole', name: 'Sinkhole', condition: 'Trophée `long_journey`', max: 1, evaluate: (g) => 0 /* Simulé */ },
];
